import { useState, useCallback, useEffect } from 'react';
import { Language, Translations } from '../types';

// Static translation dictionary
const translations: Translations = {
  [Language.EN]: {
    title: 'Intelligent Question Generator',
    welcome_subtitle: 'Generate questions from your notes in seconds.',
    welcome_upload_button: '📄 Upload Your Study File',
    welcome_upload_helper_text: 'Ensure the text is clear and correctly written.',
    upload_prompt: 'Paste your study material here, or upload a file above.',
    upload_button: 'Analyze Text',
    upload_instruction: 'Drag & drop your file here, paste text, or',
    upload_browse: 'browse files',
    upload_file_types: 'PDF, DOCX, TXT, PNG, JPG',
    parsing_file: 'Parsing your file...',
    loaded_file_label: 'Loaded file:',
    processing: 'Analyzing your text...',
    select_page_range_title: 'Which pages should I focus on?',
    select_page_range_subtitle: 'Your document has {count} pages.',
    from_page: 'From page',
    to_page: 'To page',
    continue_button: 'Continue',
    select_type_title: 'Choose Question Type',
    multiple_choice: 'Multiple Choice',
    true_false: 'True/False',
    select_count_title: 'How many questions?',
    generate_button: 'Generate Questions',
    generating: 'Generating your questions...',
    check_answer: 'Check Answer',
    next_question: 'Next Question',
    correct_feedback: 'Correct!',
    incorrect_feedback: 'Incorrect. The correct answer is:',
    more_questions: 'Generate More Questions?',
    completed_title: 'Well done!',
    completed_message: 'You have successfully completed your test. 🎉',
    error_title: 'An Error Occurred',
    error_no_text: 'Please paste some text or upload a file to analyze.',
    error_generation_failed: 'Failed to generate questions. Please try again.',
    error_parsing_failed: "Failed to parse the file. Please ensure it's a valid PDF, DOCX, TXT, or image file and try again.",
    error_invalid_page_range: 'Invalid page range. Please ensure "From" is not greater than "To".',
    powered_by: 'Powered by Gemini',
    created_by: 'Created by: Ohood Mojali',
    true: 'True',
    false: 'False',
    return_to_start: 'Return to Start',
    upload_another_file: 'Upload Another File',
    back_button: 'Back',
  },
  [Language.AR]: {
    title: 'مولّد الأسئلة الذكي',
    welcome_subtitle: 'أنشئ أسئلة من ملاحظاتك في ثوانٍ.',
    welcome_upload_button: '📄 ارفع ملفك الدراسي',
    welcome_upload_helper_text: 'احرص على ان يكون النص واضح ومكتوب بطريقة صحيحة',
    upload_prompt: 'الصق المادة الدراسية هنا، أو قم بتحميل ملف أعلاه.',
    upload_button: 'تحليل النص',
    upload_instruction: 'اسحب وأفلت ملفك هنا، أو الصق النص، أو',
    upload_browse: 'تصفح الملفات',
    upload_file_types: 'PDF, DOCX, TXT, PNG, JPG',
    parsing_file: 'جاري تحليل ملفك...',
    loaded_file_label: 'الملف المحمل:',
    processing: 'جاري تحليل النص...',
    select_page_range_title: 'أي الصفحات تريد التركيز عليها؟',
    select_page_range_subtitle: 'يحتوي مستندك على {count} من الصفحات.',
    from_page: 'من صفحة',
    to_page: 'إلى صفحة',
    continue_button: 'متابعة',
    select_type_title: 'اختر نوع الأسئلة',
    multiple_choice: 'اختيار من متعدد',
    true_false: 'صح / خطأ',
    select_count_title: 'كم عدد الأسئلة؟',
    generate_button: 'توليد الأسئلة',
    generating: 'جاري توليد أسئلتك...',
    check_answer: 'تحقق من الإجابة',
    next_question: 'السؤال التالي',
    correct_feedback: 'صحيح!',
    incorrect_feedback: 'غير صحيح. الإجابة الصحيحة هي:',
    more_questions: 'هل تريد المزيد من الأسئلة؟',
    completed_title: 'أحسنت!',
    completed_message: 'لقد أكملت اختبارك بنجاح. 🎉',
    error_title: 'حدث خطأ',
    error_no_text: 'يرجى لصق بعض النص أو تحميل ملف لتحليله.',
    error_generation_failed: 'فشل توليد الأسئلة. يرجى المحاولة مرة أخرى.',
    error_parsing_failed: "فشل في تحليل الملف. يرجى التأكد من أنه ملف PDF أو DOCX أو TXT أو صورة صالح والمحاولة مرة أخرى.",
    error_invalid_page_range: 'نطاق الصفحات غير صالح. يرجى التأكد من أن صفحة البداية ليست أكبر من صفحة النهاية.',
    powered_by: 'مدعوم بواسطة Gemini',
    created_by: 'تم الإنشاء بواسطة: عهود مجلي',
    true: 'صح',
    false: 'خطأ',
    return_to_start: 'الرجوع للبداية',
    upload_another_file: 'رفع ملف آخر',
    back_button: 'رجوع',
  },
  [Language.ZH]: {
    title: '智能问题生成器',
    welcome_subtitle: '几秒钟内从您的笔记生成问题。',
    welcome_upload_button: '📄 上传您的学习文件',
    welcome_upload_helper_text: '确保文本清晰且书写正确。',
    upload_prompt: '在此处粘贴您的学习材料，或上传上面的文件。',
    upload_button: '分析文本',
    upload_instruction: '将文件拖放到此处，粘贴文本，或',
    upload_browse: '浏览文件',
    upload_file_types: 'PDF, DOCX, TXT, PNG, JPG',
    parsing_file: '正在解析您的文件...',
    loaded_file_label: '已加载文件：',
    processing: '正在分析您的文本...',
    select_page_range_title: '您想关注哪些页面？',
    select_page_range_subtitle: '您的文档有 {count} 页。',
    from_page: '从页面',
    to_page: '到页面',
    continue_button: '继续',
    select_type_title: '选择问题类型',
    multiple_choice: '多项选择',
    true_false: '是非题',
    select_count_title: '需要多少个问题？',
    generate_button: '生成问题',
    generating: '正在生成您的问题...',
    check_answer: '检查答案',
    next_question: '下一个问题',
    correct_feedback: '正确！',
    incorrect_feedback: '不正确。正确答案是：',
    more_questions: '生成更多问题？',
    completed_title: '做得好！',
    completed_message: '您已成功完成测试。 🎉',
    error_title: '发生错误',
    error_no_text: '请粘贴一些文本或上传文件进行分析。',
    error_generation_failed: '生成问题失败。请再试一次。',
    error_parsing_failed: "解析文件失败。请确保它是有效的 PDF、DOCX、TXT 或图像文件，然后重试。",
    error_invalid_page_range: '无效的页面范围。请确保“从”不大于“到”。',
    powered_by: '由 Gemini 提供支持',
    created_by: '创建者： Ohood Mojali',
    true: '是',
    false: '非',
    return_to_start: '返回首页',
    upload_another_file: '上传另一个文件',
    back_button: '返回',
  },
  [Language.KO]: {
    title: '지능형 질문 생성기',
    welcome_subtitle: '몇 초 만에 노트에서 질문을 생성하세요.',
    welcome_upload_button: '📄 학습 파일 업로드',
    welcome_upload_helper_text: '텍스트가 명확하고 올바르게 작성되었는지 확인하십시오.',
    upload_prompt: '여기에 학습 자료를 붙여넣거나 위의 파일을 업로드하세요.',
    upload_button: '텍스트 분석',
    upload_instruction: '여기에 파일을 드래그 앤 드롭하거나, 텍스트를 붙여넣거나,',
    upload_browse: '파일 찾아보기',
    upload_file_types: 'PDF, DOCX, TXT, PNG, JPG',
    parsing_file: '파일을 분석 중입니다...',
    loaded_file_label: '로드된 파일:',
    processing: '텍스트를 분석 중입니다...',
    select_page_range_title: '어떤 페이지에 집중하시겠습니까?',
    select_page_range_subtitle: '문서에 {count}페이지가 있습니다.',
    from_page: '페이지부터',
    to_page: '페이지까지',
    continue_button: '계 продол',
    select_type_title: '질문 유형 선택',
    multiple_choice: '객관식',
    true_false: '참/거짓',
    select_count_title: '몇 개의 질문이 필요하신가요?',
    generate_button: '질문 생성',
    generating: '질문을 생성 중입니다...',
    check_answer: '답변 확인',
    next_question: '다음 질문',
    correct_feedback: '정답입니다!',
    incorrect_feedback: '오답입니다. 정답은 다음과 같습니다:',
    more_questions: '더 많은 질문을 생성하시겠습니까?',
    completed_title: '잘 하셨습니다!',
    completed_message: '테스트를 성공적으로 완료했습니다. 🎉',
    error_title: '오류가 발생했습니다',
    error_no_text: '분석할 텍스트를 붙여넣거나 파일을 업로드해 주세요.',
    error_generation_failed: '질문 생성에 실패했습니다. 다시 시도해 주세요.',
    error_parsing_failed: "파일 분석에 실패했습니다. 유효한 PDF, DOCX, TXT 또는 이미지 파일인지 확인하고 다시 시도하십시오.",
    error_invalid_page_range: '잘못된 페이지 범위입니다. "시작"이 "끝"보다 크지 않은지 확인하십시오.',
    powered_by: 'Gemini 제공',
    created_by: '만든 사람: Ohood Mojali',
    true: '참',
    false: '거짓',
    return_to_start: '처음으로 돌아가기',
    upload_another_file: '다른 파일 업로드',
    back_button: '뒤로',
  },
};

/**
 * Custom hook to manage application localization.
 * @returns An object containing the current language, a function to set the language,
 *          and a translation function `t`.
 */
export const useLocalization = () => {
  const [language, setLanguage] = useState<Language>(Language.EN);

  useEffect(() => {
    // Set the lang attribute on the HTML element for CSS font selection
    document.documentElement.lang = language;
    // Set text direction for Arabic
    document.documentElement.dir = language === Language.AR ? 'rtl' : 'ltr';
  }, [language]);

  const t = useCallback(
    (key: string): string => {
      return translations[language][key] || key;
    },
    [language]
  );

  return { language, setLanguage, t };
};